fix(deps): downgrade utoipa-swagger-ui to 9.0.0 (#1194)
Transitive dependency `zip` is broken on 9.0.1.

    Command failed: cargo update --config net.git-fetch-with-cli=true --manifest-path lib/Cargo.toml
        Updating crates.io index
    error: failed to select a version for the requirement `zip = "^2.6"`
      version 2.6.0 is yanked
      version 2.6.1 is yanked
    location searched: crates.io index
    required by package `utoipa-swagger-ui v9.0.1`
        ... which satisfies dependency `utoipa-swagger-ui = "=9.0.1"` of package `radiojournal-api v0.4.4 (/tmp/renovate/repos/github/fluxth/radiojournal/api)`